<Workspace Version="1.0.0.1180" X="-244.813339546018" Y="-469.837107002276" zoom="1.96586738035265" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.Directory guid="35265560-afc1-43d6-aefc-10dfa84442eb" type="CoreNodeModels.Input.Directory" nickname="Files to Upgrade" x="191.5" y="318" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>..</System.String>
    </CoreNodeModels.Input.Directory>
    <PythonNodeModels.PythonNode guid="d8363353-80ab-4a88-a730-c97478759372" type="PythonNodeModels.PythonNode" nickname="Upgrade RFAs" x="466.5" y="361" isVisible="false" isUpstreamVisible="false" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <Script>import sys
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib");
import os
import clr

clr.AddReference('ProtoGeometry')
clr.AddReference('RevitNodes')
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager

from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN
a=[]
r=[]
app = DocumentManager.Instance.CurrentUIApplication.Application

for dir,subdirlist,files in os.walk(IN[0]):  
  for file in files:
    if file.endswith(".rfa"):
      f = str(dir + "\\" + file)
      a.append(f)
      d = app.OpenDocumentFile(f)
      subpath = ""      
      if len(subdirlist) == 0:
        subpath = IN[1] + "\\" + os.path.basename(dir) + "\\"
        if not os.path.exists(subpath):
          #create dir to be able to write to
          os.makedirs(subpath)
      else:
        subpath= IN[1] + "\\"

      newf = subpath + file
      d.SaveAs(newf)
      d.Close()
      r.append(newf)

#remove backups
for dir,subdirlist,files in os.walk(IN[1]):
  for file in files:
    if file.endswith(".0001.rfa"):
      ftd = dir + "\\" + file
      os.remove(ftd)

#test for success
res = False
if len(a) == len(r):
  res = True

#Assign your output to the OUT variable.
OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.Directory guid="beb1cd42-c38f-4585-b2b8-a69a5efd1146" type="CoreNodeModels.Input.Directory" nickname="Path to Save Files" x="197.532272157698" y="411.354848105132" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>..</System.String>
    </CoreNodeModels.Input.Directory>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="35265560-afc1-43d6-aefc-10dfa84442eb" start_index="0" end="d8363353-80ab-4a88-a730-c97478759372" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="beb1cd42-c38f-4585-b2b8-a69a5efd1146" start_index="0" end="d8363353-80ab-4a88-a730-c97478759372" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="ca3e4ef6-b3f1-45ca-986b-594820d0e49b" annotationText="RFA Upgrade" left="181.5" top="288" width="417" height="215.354848105132" fontSize="14" InitialTop="318" InitialHeight="222" TextblockHeight="20" backgrouund="#FFC1D676">
      <Models ModelGuid="35265560-afc1-43d6-aefc-10dfa84442eb" />
      <Models ModelGuid="d8363353-80ab-4a88-a730-c97478759372" />
      <Models ModelGuid="beb1cd42-c38f-4585-b2b8-a69a5efd1146" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>